
export const TRANSLATIONS = {
  en: {
    dashboard: "Dashboard",
    myTasks: "My Tasks",
    projects: "Projects",
    analytics: "Analytics",
    settings: "Settings",
    tips: "Expert Tips",
    welcome: "Welcome back",
    totalTasks: "Total Tasks",
    completed: "Completed",
    active: "Active",
    quickAdd: "Add Quick Task",
    recentTasks: "Recent Tasks",
    viewAll: "View All",
    tipTitle: "Daily Insight",
    createTask: "Create New Task",
    allTasks: "All Tasks",
    searchPlaceholder: "Search tasks...",
    noTasks: "No tasks found",
    appearance: "Appearance",
    theme: "Display Theme",
    lightMode: "Light",
    darkMode: "Dark",
    localization: "Localization",
    language: "App Language",
    dataManagement: "Data Management",
    export: "Export Workspace",
    import: "Import Workspace",
    cancel: "Cancel",
    update: "Update Task",
    create: "Create Task",
    priority: "Priority",
    project: "Project",
    dueDate: "Due Date",
    description: "Description",
    title: "Task Title",
    productivity: "Productivity",
    low: "Low",
    medium: "Medium",
    high: "High",
    general: "General",
    personal: "Personal",
    work: "Work",
    notifications: "Notifications",
    notifDesc: "Get alerts for due tasks",
    reset: "Reset Data",
    resetDesc: "Wipe all tasks and settings",
    successImport: "Data imported successfully!",
    errorImport: "Invalid data file.",
    confirmReset: "Are you sure? This cannot be undone.",
    exploreTips: "Explore All Tips",
    tipsHero: "Optimize Your Performance",
    tipsSub: "Curated strategies from global performance experts to help you reclaim your time."
  },
  fr: {
    dashboard: "Tableau de bord",
    myTasks: "Mes tâches",
    projects: "Projets",
    analytics: "Analyses",
    settings: "Paramètres",
    tips: "Conseils d'Experts",
    welcome: "Bon retour",
    totalTasks: "Tâches totales",
    completed: "Terminées",
    active: "Actives",
    quickAdd: "Ajout rapide",
    recentTasks: "Tâches récentes",
    viewAll: "Voir tout",
    tipTitle: "Conseil du Jour",
    createTask: "Nouvelle tâche",
    allTasks: "Toutes les tâches",
    searchPlaceholder: "Rechercher...",
    noTasks: "Aucune tâche trouvée",
    appearance: "Apparence",
    theme: "Thème d'affichage",
    lightMode: "Clair",
    darkMode: "Sombre",
    localization: "Localisation",
    language: "Langue de l'application",
    dataManagement: "Gestion des données",
    export: "Exporter l'espace",
    import: "Importer l'espace",
    cancel: "Annuler",
    update: "Mettre à jour",
    create: "Créer la tâche",
    priority: "Priorité",
    project: "Projet",
    dueDate: "Date d'échéance",
    description: "Description",
    title: "Titre de la tâche",
    productivity: "Productivité",
    low: "Basse",
    medium: "Moyenne",
    high: "Haute",
    general: "Général",
    personal: "Personnel",
    work: "Travail",
    notifications: "Notifications",
    notifDesc: "Recevoir des alertes pour les tâches",
    reset: "Réinitialiser",
    resetDesc: "Effacer toutes les tâches et paramètres",
    successImport: "Données importées avec succès!",
    errorImport: "Fichier de données invalide.",
    confirmReset: "Êtes-vous sûr ? Cette action est irréversible.",
    exploreTips: "Découvrir tous les conseils",
    tipsHero: "Optimisez vos performances",
    tipsSub: "Stratégies sélectionnées par des experts mondiaux pour vous aider à regagner votre temps."
  },
  sw: {
    dashboard: "Dashibodi",
    myTasks: "Kazi Zangu",
    projects: "Miradi",
    analytics: "Takwimu",
    settings: "Mipangilio",
    tips: "Ushauri wa Kitaalam",
    welcome: "Karibu tena",
    totalTasks: "Jumla ya Kazi",
    completed: "Zilizokamilika",
    active: "Zinazoendelea",
    quickAdd: "Ongeza Kazi Haraka",
    recentTasks: "Kazi za Hivi Karibuni",
    viewAll: "Ona Zote",
    tipTitle: "Ufahamu wa Leo",
    createTask: "Unda Kazi Mpya",
    allTasks: "Kazi Zote",
    searchPlaceholder: "Tafuta kazi...",
    noTasks: "Hakuna kazi iliyopatikana",
    appearance: "Muonekano",
    theme: "Mandhari ya Skrini",
    lightMode: "Mwangaza",
    darkMode: "Giza",
    localization: "Eneo",
    language: "Lugha ya Programu",
    dataManagement: "Usimamizi wa Data",
    export: "Toa Nakala ya Kazi",
    import: "Ingiza Nakala ya Kazi",
    cancel: "Ghairi",
    update: "Sasisha Kazi",
    create: "Unda Kazi",
    priority: "Umuhimu",
    project: "Mradi",
    dueDate: "Tarehe ya Mwisho",
    description: "Maelezo",
    title: "Kichwa cha Kazi",
    productivity: "Uzalishaji",
    low: "Chini",
    medium: "Kati",
    high: "Juu",
    general: "Kawaida",
    personal: "Binafsi",
    work: "Kazi",
    notifications: "Taarifa",
    notifDesc: "Pata taarifa za kazi zinazokaribia",
    reset: "Futa Kila Kitu",
    resetDesc: "Futa kazi zote na mipangilio",
    successImport: "Data imeingizwa kwa mafanikio!",
    errorImport: "Faili ya data sio sahihi.",
    confirmReset: "Una uhakika? Hii haiwezi kubadilishwa.",
    exploreTips: "Gundua Ushauri Wote",
    tipsHero: "Boresha Utendaji Wako",
    tipsSub: "Mikakati iliyochaguliwa kutoka kwa wataalamu wa kimataifa wa utendaji ili kukusaidia kudai tena muda wako."
  }
};
